name: promptus
description: A new Flutter project for promptus app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.2.8
  shared_preferences: ^2.2.1
  google_fonts: ^6.2.0
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.0
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  flutter_background_service: ^5.0.5
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  iconsax: ^0.0.8
  flutter_quill: ^11.5.0
  flutter_timezone: ^5.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
